# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Ziwen Zhang — Academic researcher in Astronomy. Showcasing my research progress and publications.'
    keywords:
      - Ziwen Zhang
      - Astronomy
      - Research
      - Academic
      - Publications
      - Science
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: "HX02XF3gPm_FuE-TjEqt8WJX0HMZJeet3-bGdiOG07Y"   # Google Search Console 验证码

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Ziwen Zhang"

# Site footer
footer:
  copyright:
    notice: '© {year} Ziwen Zhang. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

custom_css:
  - css/custom.css

baseURL: "https://ziwenkk.github.io/ziwen.github.io/"
languageCode: "en-us"
title: "Ziwen Hugo Site"
theme: "Ziwen homepage"

enableRobotsTXT: true
